=== jayasurya2606/EP-Practical/Exp 1/WebContent/Task2.dtd
<!ELEMENT Students_info (student+)>
<!ELEMENT student (name, id, regno, avg, dob, time, mobile, distinction)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT regno (#PCDATA)>
<!ELEMENT avg (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT distinction (#PCDATA)>

=== jayasurya2606/EP-Practical/Exp 1/WebContent/Task2.xml
<!DOCTYPE Students_info SYSTEM "Task2.dtd">
<Students_info>
	<student>
		<name>Surya</name>
		<id>001</id>
		<regno>190031733</regno>
		<avg>92</avg>
		<dob>26-06-2002</dob>
		<time>11:34 AM</time>
		<mobile>8328620294</mobile>
		<distinction>YES</distinction>
	</student>
	<student>
		<name>Sadiq</name>
		<id>002</id>
		<regno>190031506</regno>
		<avg>88</avg>
		<dob>18-09-2001</dob>
		<time>11:35 AM</time>
		<mobile>8790424533</mobile>
		<distinction>YES</distinction>
	</student>
	<student>
		<name>Sharooq</name>
		<id>003</id>
		<regno>190031479</regno>
		<avg>90</avg>
		<dob>10-02-2002</dob>
		<time>11:36 AM</time>
		<mobile>9391402909</mobile>
		<distinction>YES</distinction>
	</student>
	<student>
		<name>Naveen</name>
		<id>004</id>
		<regno>190030230</regno>
		<avg>94</avg>
		<dob>22-06-2002</dob>
		<time>11:41 AM</time>
		<mobile>7095032594</mobile>
		<distinction>YES</distinction>
	</student>
	<student>
		<name>Ganesh</name>
		<id>005</id>
		<regno>190030122</regno>
		<avg>80</avg>
		<dob>10-03-2002</dob>
		<time>11:44 AM</time>
		<mobile>9658125433</mobile>
		<distinction>YES</distinction>
	</student>
</Students_info>
