=== jayasurya2606/EP-Practical/Exp 1/WebContent/Task1.dtd
<!ELEMENT Students (student+)>
<!ELEMENT student (name, id, cgpa, Branch)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT cgpa (#PCDATA)>
<!ELEMENT Branch (#PCDATA)>

=== jayasurya2606/EP-Practical/Exp 1/WebContent/Task1.xml
<!DOCTYPE Students SYSTEM "Task1.dtd">
<Students>
	<student>
		<name>Surya</name>
		<id>001</id>
		<cgpa>8.7</cgpa>
		<Branch>CSE</Branch>
	</student>
	<student>
		<name>Sadiq</name>
		<id>002</id>
		<cgpa>8.5</cgpa>
		<Branch>CSE</Branch>
	</student>
	<student>
		<name>Sharooq</name>
		<id>003</id>
		<cgpa>9.0</cgpa>
		<Branch>CSE</Branch>
	</student>
	<student>
		<name>Naveen</name>
		<id>004</id>
		<cgpa>9.2</cgpa>
		<Branch>ECE</Branch>
	</student>
	<student>
		<name>Ganesh</name>
		<id>005</id>
		<cgpa>8.0</cgpa>
		<Branch>ME</Branch>
	</student>
</Students>
